[package]
name = "msi-klc"
version = "1.0.0"
edition = "2021"
authors = ["ErrorNoInternet <error.nointernet@gmail.com>"]
license = "MIT"
description = "MSI Keyboard Light Controller"
homepage = "https://github.com/errorNoInternet/msi-klc"
repository = "https://github.com/errorNoInternet/msi-klc"
readme = "README.md"
keywords = ["msi", "laptop", "rgb", "backlight", "steelseries"]
exclude = ["animations/*", "src/main.rs", "src/parser.rs"]

[dependencies]
clap = "3.2.22"
hidapi = "1.4.2"
